import { 
  Code2, 
  Globe, 
  Layers, 
  Cpu, 
  Smartphone, 
  Database, 
  Terminal, 
  Figma, 
  Youtube, 
  FileText, 
  Github, 
  ExternalLink,
  Award,
  Trophy,
  Calendar,
  MapPin,
  Link as LinkIcon
} from "lucide-react";

export const skills = [
  { name: "HTML", icon: Globe, color: "#e34f26" },
  { name: "CSS", icon: Layers, color: "#1572b6" },
  { name: "React.js", icon: Globe, color: "#61dafb" },
  { name: "JavaScript", icon: Code2, color: "#f7df1e" },
  { name: "C", icon: Terminal, color: "#00599C" },
  { name: "C++", icon: Terminal, color: "#00599C" },
  { name: "Node.js", icon: Cpu, color: "#339933" },
  { name: "Express.js", icon: Cpu, color: "#000000" },
  { name: "MongoDB", icon: Database, color: "#47a248" },
  { name: "MySQL", icon: Database, color: "#4479a1" },
  { name: "Figma", icon: Figma, color: "#f24e1e" },
  { name: "Canva", icon: Figma, color: "#00c4cc" },
  { name: "Git", icon: Github, color: "#f05032" },
  { name: "GitHub", icon: Github, color: "#24292e" },
];

export const projects = [
  {
    id: "p1",
    title: "Axionix AI - YouTube Analytics Platform",
    description: "Engineered an AI-powered YouTube analytics platform that analyzes 1000+ comments in under 30 seconds using LLM-driven sentiment analysis with 87% accuracy across 23+ Indian languages. Developed Smart Reply generation for contextual, channel-voice-matched responses, an AI Content Idea Generator that identifies audience requests and predicts video performance, and an Analytics Dashboard with exportable PDF reports. Implemented secure JWT authentication, multi-language NLP pipelines, and a complete REST API with Postman collection for seamless integration.",
    tags: ["Next.js", "MongoDB", "LLM", "TypeScript", "Tailwind CSS"],
    category: "Full Stack",
    github: "https://github.com/Aashish-gif/Axion-Ai",
    live: "https://axionixai.vercel.app/",
    youtube: "https://www.youtube.com/watch?v=-uyjXu-hBr4",
    postman: "https://documenter.getpostman.com/view/39216526/2sBXinFUwH",
    image: "https://images.unsplash.com/photo-1611162616475-46b635cb6868?q=80&w=2000&auto=format&fit=crop",
  },
  {
    id: "p2",
    title: "Zenith AI - The Ultimate Cloud Synthesis",
    description: "Built an AI-powered cloud infrastructure platform with visual drag-and-drop interface for real-time Terraform code generation. Implemented RAG to ensure syntax accuracy by retrieving official documentation, achieving zero-error outputs. Developed Intent Analysis engine for automatic IAM policy and security configuration generation. Created AI Budget Architect and Postman collection for cost optimization and seamless API integration.",
    tags: ["React.js", "Node.js", "React Flow", "RAG", "LLM", "Express", "MongoDB"],
    category: "Full Stack",
    github: "https://github.com/Aashish-gif/InnovAItion-X-DAIICT-HACKATON-",
    live: "https://zenith-ai-ultimate-cloud-synthesis.netlify.app/",
    youtube: "https://youtu.be/InXvgrVhvIs?si=A1TLU7Ac_YtXV5mu",
    postman: "https://documenter.getpostman.com/view/39216526/2sBXc7Kiys",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2000&auto=format&fit=crop",
  },
  {
    id: "p3",
    title: "Worknix – The All-in-One Corporate Operating System",
    description: "Designed a centralized platform reducing 30–40% time loss on manual HR, payroll, attendance, and project management for 200+ employees. Unified workflows with automated reporting, real-time dashboards, and role-based access control into a single system. Automated approvals cutting task delays by 50% and added dynamic notifications to reduce email dependency. Replaced siloed tools with an integrated system, improving overall team productivity.",
    tags: ["React.js", "Node.js", "MongoDB", "Figma"],
    category: "Full Stack",
    github: "https://github.com/codinggita/worknix.git",
    live: "https://worknix-the-all-in-one-corporate-os.netlify.app/",
    youtube: "https://www.youtube.com/watch?v=gZLKio8cW0g",
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=2000&auto=format&fit=crop",
  },
   {
  id: "p4",
  title: "VoltC – Real-Time C Compiler IDE",
  description:
    "Built a browser-based C programming IDE for rapid prototyping with real-time compilation, debugging, and memory visualization. Developed a custom C compiler and VM runtime that compiles C into a simplified ISA and executes programs directly in-browser with trace-based debugging. Added Monaco-powered editing with syntax validation, formatting, auto-save, and multi-file management for a seamless developer experience. Integrated GitHub OAuth with repository creation, file import/export, and direct push support, enabling complete cloud-based coding workflows. Implemented execution tracing, stack/register visualization, and step-by-step debugging tools to simplify low-level program analysis and recursive execution debugging.",
  tags: [
    "React.js","TypeScript","Node.js","Express.js","Tailwind CSS","Monaco Editor","C","GitHub OAuth","Vite"
  ],
  category: "Full Stack",
  github: "https://github.com/Aashish-gif/Doppelganger---March-2026-T",
  live: "https://doppelganger-kappa.vercel.app/",
  image:
    "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?q=80&w=2000&auto=format&fit=crop",
},
{
  id: "p5",
  title: "YantraCare – Equipment Maintenance Management System",
  description:
    "Built a full-stack equipment maintenance management platform during the Odoo x Adani University Hackathon in just 8 hours. Developed a centralized system for tracking equipment lifecycle, handling preventive and corrective maintenance requests, and coordinating maintenance teams efficiently. Implemented role-based dashboards, Kanban workflows, calendar-based scheduling, and real-time analytics to streamline maintenance operations and reduce downtime. Added JWT-based authentication, team assignment workflows, drag-and-drop task management, and responsive dashboards for admins, managers, technicians, and employees. Designed scalable REST APIs with MongoDB-backed data models supporting equipment tracking, maintenance scheduling, team management, and operational insights.",
  tags: ["React.js", "TypeScript", "Node.js", "Express.js", "MongoDB", "Tailwind CSS", "Shadcn UI", "JWT", "FullCalendar", "Vite"],
  category: "Full Stack",
  github: "https://github.com/Aashish-gif/Adani-VirtualRound",
  live: "https://yantra-care.vercel.app/login",
  image: "https://images.unsplash.com/photo-1581092921461-eab62e97a780?q=80&w=2000&auto=format&fit=crop",
},
{
  id: "p6",
  title: "EcoSetu – Smart Waste Management & Sustainability Platform",
  description:
    "Developed a full-stack sustainability management platform during the Odoo x Adani Hackathon to streamline waste collection, tracking, and recycling operations. Built role-based workflows enabling citizens, collectors, and administrators to efficiently manage waste reporting, pickup scheduling, and sustainability initiatives from a centralized dashboard. Implemented real-time analytics, smart tracking systems, and responsive dashboards to improve operational visibility and optimize waste management processes. Added secure authentication, dynamic notifications, and scalable REST APIs to support seamless coordination between users and waste management teams. Designed a clean and responsive UI focused on accessibility, productivity, and environmental impact awareness.",
  tags: ["React.js", "TypeScript", "Node.js", "Express.js", "MongoDB", "Tailwind CSS", "JWT", "REST API", "Vite", "Shadcn UI"],
  category: "Full Stack",
  github: "https://github.com/Aashish-gif/OdooXadani-team-CodingKarma",
  live: "https://eco-setu.vercel.app/login",
  image: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?q=80&w=2000&auto=format&fit=crop",
},
{
  id: "p7",
  title: "Cricket Scores by TAJ – Live Cricket Scoring Platform",
  description:
    "Built a real-time cricket scoring platform delivering live match updates, score tracking, and match statistics through a responsive web interface. Developed dynamic match dashboards displaying live scores, innings summaries, player performance, and ongoing match status for an engaging user experience. Implemented REST API integration, real-time data rendering, and optimized frontend state management to ensure smooth score updates with minimal latency. Designed a clean and mobile-friendly UI focused on fast navigation, accessibility, and seamless cricket match monitoring for users across devices.",
  tags: ["React.js", "Node.js", "Express.js", "MongoDB", "REST API", "Tailwind CSS", "JavaScript", "Render"],
  category: "Full Stack",
  github: "https://github.com/Aashish-gif/Cricket_Score_By_TAJ",
  live: "https://cricket-scores-by-taj.onrender.com/",
  image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?q=80&w=2000&auto=format&fit=crop",
},
{
  id: "p8",
  title: "GitHub Data Management System",
  description:
    "Developed a backend-driven GitHub data management platform to manage and retrieve repository-related information including users, repositories, pull requests, issues, commits, forks, and stars. Designed scalable RESTful APIs for efficient data retrieval, filtering, and manipulation while ensuring optimized backend performance. Integrated MongoDB for structured storage and management of GitHub metadata with secure and maintainable database schemas. Documented all API endpoints using Postman to simplify testing, collaboration, and third-party integration workflows. Deployed the backend system on Render for reliable cloud-based access and API availability.",
  tags: ["Node.js", "Express.js", "MongoDB", "REST API", "Postman", "Render", "JavaScript"],
  category: "Backend Development",
  github: "https://github.com/Aashish-gif/ClassTest",
  postman: "https://documenter.getpostman.com/view/39216526/2sAYQUptVD",
  image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?q=80&w=2000&auto=format&fit=crop",
},
{
  id: "p9",
  title: "Step Spring Shoes – E-Commerce Website Clone",
  description:
    "Developed a responsive e-commerce website clone inspired by the official Step Spring Shoes platform using HTML and CSS. Recreated a modern and visually appealing shopping experience with structured product showcase sections, intuitive navigation, and clean UI layouts focused on user engagement. Designed responsive pages optimized for desktop and mobile browsing while maintaining consistent styling and accessibility. Implemented sleek landing sections, promotional banners, and organized product displays to replicate a real-world footwear brand experience and strengthen frontend development skills.",
  tags: ["HTML", "CSS", "Responsive Design", "Frontend Development", "Web Design"],
  category: "HTML/CSS",
  github: "https://github.com/Aashish-gif/Spring_Step_website",
  live: "https://spring-step-official-website.onrender.com",
  youtube: "#",
  postman: "#",
  image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2000&auto=format&fit=crop",
},
];

export const certificates = [
  {
    id: "c1",
    name: "IIT Gandhinagar Hackathon Certificate",
    issuer: "IIT Gandhinagar x Oddo",
    date: "2025",
    link: "https://drive.google.com/drive/folders/1SG-nN02_YTscvPvpGiGwJ3YpWZTbLTMA?usp=sharing",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c2",
    name: "IIIT Naya Raipur Hackathon Certificate",
    issuer: "IIIT Naya Raipur x GDG Raipur",
    date: "2025",
    link: "https://drive.google.com/drive/folders/1SG-nN02_YTscvPvpGiGwJ3YpWZTbLTMA?usp=sharing",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c3",
    name: "Tech Expo Ahmedabad Certificate",
    issuer: "Tech Expo Ahmedabad",
    date: "2025",
    link: "https://drive.google.com/drive/folders/1SG-nN02_YTscvPvpGiGwJ3YpWZTbLTMA?usp=sharing",
    verified: true,
    category: "Competition",
  },
  {
    id: "c4",
    name: "IIIT Surat Hackathon Certificate",
    issuer: "IIIT Surat x CodingGita",
    date: "2025",
    link: "https://drive.google.com/drive/folders/1SG-nN02_YTscvPvpGiGwJ3YpWZTbLTMA?usp=sharing",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c5",
    name: "Academic Excellence Certificate",
    issuer: "CodingGita X Rai University",
    date: "2025",
    link: "https://drive.google.com/drive/folders/1SG-nN02_YTscvPvpGiGwJ3YpWZTbLTMA?usp=sharing",
    verified: true,
    category: "Academic",
  },
  {
    id: "c6",
    name: "Programming Excellence Certificate",
    issuer: "CodingGita X Rai University",
    date: "2025",
    link: "https://drive.google.com/drive/folders/1SG-nN02_YTscvPvpGiGwJ3YpWZTbLTMA?usp=sharing",
    verified: true,
    category: "Academic",
  },
];

export const hackathons = [
  {
    id: "h1",
    name: "IIT Gandhinagar x Oddo Hackathon",
    position: "Finalist",
    date: "8-9 November 2025",
    description: "Participated in a national-level hackathon organized by IIT Gandhinagar in collaboration with Oddo; advanced through all rounds and selected as a finalist among under 100 teams from over 5,000 participating teams by building an innovative full-stack solution.",
    certificate: "https://drive.google.com/file/d/1RLYaHOZQWR86ehYx3s43DHk7PwCOByM8/view",
    photos: ["#"],
    location: "IIT Gandhinagar",
    projectLink: "#",
  },
  {
    id: "h2",
    name: "IIIT Surat ",
    position: "1st Rank",
    date: "13-15 February 2026",
    description: "Achieved 1st rank in a competitive hackathon organized by IIIT Surat Demonstrated exceptional problem-solving skills and technical expertise in developing innovative solutions under time constraints.",
    certificate: "https://drive.google.com/file/d/1HbOl1P_grH1Y_a3xRim7cj9m-w1a7zmE/view?usp=sharing",
    photos: ["#"],
    location: "IIIT Surat",
    projectLink: "#",
  },
  
   
  {
    id: "h3",
    name: "Tech Expo Ahmedabad",
    position: "2nd Runner-Up",
    date: "27-28 February2025",
    description: "Showcased innovative projects at Tech Expo Ahmedabad 2025. Demonstrated hands-on full-stack development skills and problem-solving, securing 2nd Runner-Up solo participant among 55+ teams.",
    certificate: "https://drive.google.com/file/d/1fTOV7WWLn9X3HTYQk6Hoseftv_qIkebz/view",
    photos: ["#"],
    location: "Ahmedabad, Gujarat",
    projectLink: "#",
  },
 
];
