import { 
  Code2, 
  Globe, 
  Layers, 
  Cpu, 
  Smartphone, 
  Database, 
  Terminal, 
  Figma, 
  Youtube, 
  FileText, 
  Github, 
  ExternalLink,
  Award,
  Trophy,
  Calendar,
  MapPin,
  Link as LinkIcon
} from "lucide-react";

export const skills = [
  { name: "HTML", icon: Globe, color: "#e34f26" },
  { name: "CSS", icon: Layers, color: "#1572b6" },
  { name: "React.js", icon: Globe, color: "#61dafb" },
  { name: "JavaScript", icon: Code2, color: "#f7df1e" },
  { name: "C", icon: Terminal, color: "#00599C" },
  { name: "C++", icon: Terminal, color: "#00599C" },
  { name: "Node.js", icon: Cpu, color: "#339933" },
  { name: "Express.js", icon: Cpu, color: "#000000" },
  { name: "MongoDB", icon: Database, color: "#47a248" },
  { name: "MySQL", icon: Database, color: "#4479a1" },
  { name: "Figma", icon: Figma, color: "#f24e1e" },
  { name: "Canva", icon: Figma, color: "#00c4cc" },
  { name: "Git", icon: Github, color: "#f05032" },
  { name: "GitHub", icon: Github, color: "#24292e" },
];

export const projects = [
  {
    id: "p1",
    title: "Axionix AI - YouTube Analytics Platform",
    description: "Engineered an AI-powered YouTube analytics platform that analyzes 1000+ comments in under 30 seconds using LLM-driven sentiment analysis with 87% accuracy across 23+ Indian languages. Developed Smart Reply generation for contextual, channel-voice-matched responses, an AI Content Idea Generator that identifies audience requests and predicts video performance, and an Analytics Dashboard with exportable PDF reports. Implemented secure JWT authentication, multi-language NLP pipelines, and a complete REST API with Postman collection for seamless integration.",
    tags: ["Next.js", "MongoDB", "LLM", "TypeScript", "Tailwind CSS"],
    category: "Full Stack",
    github: "https://github.com/Aashish-gif/Axion-Ai",
    live: "https://axionixai.vercel.app/",
    youtube: "https://www.youtube.com/watch?v=-uyjXu-hBr4",
    postman: "https://documenter.getpostman.com/view/39216526/2sBXinFUwH",
    image: "https://images.unsplash.com/photo-1611162616475-46b635cb6868?q=80&w=2000&auto=format&fit=crop",
  },
  {
    id: "p2",
    title: "Zenith AI - The Ultimate Cloud Synthesis",
    description: "Built an AI-powered cloud infrastructure platform with visual drag-and-drop interface for real-time Terraform code generation. Implemented RAG to ensure syntax accuracy by retrieving official documentation, achieving zero-error outputs. Developed Intent Analysis engine for automatic IAM policy and security configuration generation. Created AI Budget Architect and Postman collection for cost optimization and seamless API integration.",
    tags: ["React.js", "Node.js", "React Flow", "RAG", "LLM", "Express", "MongoDB"],
    category: "Full Stack",
    github: "https://github.com/Aashish-gif/InnovAItion-X-DAIICT-HACKATON-",
    live: "https://zenith-ai-ultimate-cloud-synthesis.netlify.app/",
    youtube: "https://youtu.be/InXvgrVhvIs?si=A1TLU7Ac_YtXV5mu",
    postman: "https://documenter.getpostman.com/view/39216526/2sBXc7Kiys",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2000&auto=format&fit=crop",
  },
  {
    id: "p3",
    title: "Worknix – The All-in-One Corporate Operating System",
    description: "Designed a centralized platform reducing 30–40% time loss on manual HR, payroll, attendance, and project management for 200+ employees. Unified workflows with automated reporting, real-time dashboards, and role-based access control into a single system. Automated approvals cutting task delays by 50% and added dynamic notifications to reduce email dependency. Replaced siloed tools with an integrated system, improving overall team productivity.",
    tags: ["React.js", "Node.js", "MongoDB", "Figma"],
    category: "Full Stack",
    github: "https://github.com/codinggita/worknix.git",
    live: "https://worknix-the-all-in-one-corporate-os.netlify.app/",
    youtube: "https://www.youtube.com/watch?v=gZLKio8cW0g",
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=2000&auto=format&fit=crop",
  },
   {
  id: "p4",
  title: "VoltC – Real-Time C Compiler IDE",
  description:
    "Built a browser-based C programming IDE for rapid prototyping with real-time compilation, debugging, and memory visualization. Developed a custom C compiler and VM runtime that compiles C into a simplified ISA and executes programs directly in-browser with trace-based debugging. Added Monaco-powered editing with syntax validation, formatting, auto-save, and multi-file management for a seamless developer experience. Integrated GitHub OAuth with repository creation, file import/export, and direct push support, enabling complete cloud-based coding workflows. Implemented execution tracing, stack/register visualization, and step-by-step debugging tools to simplify low-level program analysis and recursive execution debugging.",
  tags: [
    "React.js","TypeScript","Node.js","Express.js","Tailwind CSS","Monaco Editor","C","GitHub OAuth","Vite"
  ],
  category: "Full Stack",
  github: "https://github.com/Aashish-gif/Doppelganger---March-2026-T",
  live: "https://doppelganger-kappa.vercel.app/",
  image:
    "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?q=80&w=2000&auto=format&fit=crop",
},
{
  id: "p5",
  title: "YantraCare – Equipment Maintenance Management System",
  description:
    "Built a full-stack equipment maintenance management platform during the Odoo x Adani University Hackathon in just 8 hours. Developed a centralized system for tracking equipment lifecycle, handling preventive and corrective maintenance requests, and coordinating maintenance teams efficiently. Implemented role-based dashboards, Kanban workflows, calendar-based scheduling, and real-time analytics to streamline maintenance operations and reduce downtime. Added JWT-based authentication, team assignment workflows, drag-and-drop task management, and responsive dashboards for admins, managers, technicians, and employees. Designed scalable REST APIs with MongoDB-backed data models supporting equipment tracking, maintenance scheduling, team management, and operational insights.",
  tags: ["React.js", "TypeScript", "Node.js", "Express.js", "MongoDB", "Tailwind CSS", "Shadcn UI", "JWT", "FullCalendar", "Vite"],
  category: "Full Stack",
  github: "https://github.com/Aashish-gif/Adani-VirtualRound",
  live: "https://yantra-care.vercel.app/login",
  image: "https://images.unsplash.com/photo-1581092921461-eab62e97a780?q=80&w=2000&auto=format&fit=crop",
},
{
  id: "p6",
  title: "EcoSetu – Smart Waste Management & Sustainability Platform",
  description:
    "Developed a full-stack sustainability management platform during the Odoo x Adani Hackathon to streamline waste collection, tracking, and recycling operations. Built role-based workflows enabling citizens, collectors, and administrators to efficiently manage waste reporting, pickup scheduling, and sustainability initiatives from a centralized dashboard. Implemented real-time analytics, smart tracking systems, and responsive dashboards to improve operational visibility and optimize waste management processes. Added secure authentication, dynamic notifications, and scalable REST APIs to support seamless coordination between users and waste management teams. Designed a clean and responsive UI focused on accessibility, productivity, and environmental impact awareness.",
  tags: ["React.js", "TypeScript", "Node.js", "Express.js", "MongoDB", "Tailwind CSS", "JWT", "REST API", "Vite", "Shadcn UI"],
  category: "Full Stack",
  github: "https://github.com/Aashish-gif/OdooXadani-team-CodingKarma",
  live: "https://eco-setu.vercel.app/login",
  image: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?q=80&w=2000&auto=format&fit=crop",
},
{
  id: "p7",
  title: "Cricket Scores by TAJ – Live Cricket Scoring Platform",
  description:
    "Built a real-time cricket scoring platform delivering live match updates, score tracking, and match statistics through a responsive web interface. Developed dynamic match dashboards displaying live scores, innings summaries, player performance, and ongoing match status for an engaging user experience. Implemented REST API integration, real-time data rendering, and optimized frontend state management to ensure smooth score updates with minimal latency. Designed a clean and mobile-friendly UI focused on fast navigation, accessibility, and seamless cricket match monitoring for users across devices.",
  tags: ["React.js", "Node.js", "Express.js", "MongoDB", "REST API", "Tailwind CSS", "JavaScript", "Render"],
  category: "Full Stack",
  github: "https://github.com/Aashish-gif/Cricket_Score_By_TAJ",
  live: "https://cricket-scores-by-taj.onrender.com/",
  image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?q=80&w=2000&auto=format&fit=crop",
},
{
  id: "p8",
  title: "GitHub Data Management System",
  description:
    "Developed a backend-driven GitHub data management platform to manage and retrieve repository-related information including users, repositories, pull requests, issues, commits, forks, and stars. Designed scalable RESTful APIs for efficient data retrieval, filtering, and manipulation while ensuring optimized backend performance. Integrated MongoDB for structured storage and management of GitHub metadata with secure and maintainable database schemas. Documented all API endpoints using Postman to simplify testing, collaboration, and third-party integration workflows. Deployed the backend system on Render for reliable cloud-based access and API availability.",
  tags: ["Node.js", "Express.js", "MongoDB", "REST API", "Postman", "Render", "JavaScript"],
  category: "Backend Development",
  github: "https://github.com/Aashish-gif/ClassTest",
  postman: "https://documenter.getpostman.com/view/39216526/2sAYQUptVD",
  image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?q=80&w=2000&auto=format&fit=crop",
},
{
  id: "p9",
  title: "Step Spring Shoes – E-Commerce Website Clone",
  description:
    "Developed a responsive e-commerce website clone inspired by the official Step Spring Shoes platform using HTML and CSS. Recreated a modern and visually appealing shopping experience with structured product showcase sections, intuitive navigation, and clean UI layouts focused on user engagement. Designed responsive pages optimized for desktop and mobile browsing while maintaining consistent styling and accessibility. Implemented sleek landing sections, promotional banners, and organized product displays to replicate a real-world footwear brand experience and strengthen frontend development skills.",
  tags: ["HTML", "CSS", "Responsive Design", "Frontend Development", "Web Design"],
  category: "HTML/CSS",
  github: "https://github.com/Aashish-gif/Spring_Step_website",
  live: "https://spring-step-official-website.onrender.com",
  youtube: "#",
  postman: "#",
  image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=2000&auto=format&fit=crop",
},
];

export const certificates = [
  {
    id: "c1",
    name: "Adani University Hackathon Certificate",
    issuer: "Adani University",
    date: "2026",
    link: "https://drive.google.com/file/d/1yJcn17Uv-kS_De2WncJXkl9KfAAOv745/view",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c2",
    name: "Charusat Hackaton Certificate",
    issuer: "Charusat",
    date: "2026",
    link: "https://drive.google.com/file/d/1MC61jiZiyJElXiJcBxV4HA47PiaQNnXw/view",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c3",
    name: "DAIICT Hackaton Certificate",
    issuer: "DAIICT",
    date: "2026",
    link: "https://drive.google.com/file/d/1s2z2RL36smr-U5KpfezmxnchPMtX7-AN/view",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c4",
    name: "DAIICT X Intutive InnovAItion Hackaton",
    issuer: "DAIICT",
    date: "2026",
    link: "https://drive.google.com/file/d/1_qdgPjSyO1BNXpcAFkkdZR8FeWqGYY2f/view",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c5",
    name: "Deloitte Cyber Security Certificate",
    issuer: "Deloitte",
    date: "2025",
    link: "https://drive.google.com/file/d/1OR1rAPKoAtdyPSyHoRzFZmSx5ECZ2RbN/view",
    verified: true,
    category: "Professional",
  },
  {
    id: "c6",
    name: "G.H. Raisoni College Hackaton",
    issuer: "G.H. Raisoni College",
    date: "2026",
    link: "https://drive.google.com/file/d/1EmpvRX1bxbFkYVdZcqVhor6r1C0IWW7m/view",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c7",
    name: "IIIT BHAGALPUR HACKATON Certificate",
    issuer: "IIIT Bhagalpur",
    date: "2026",
    link: "https://drive.google.com/file/d/17ZNiYp9VPrprDSqoHceK5uLvO5pz5eSu/view",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c8",
    name: "IIIT PRAGAY RAJ HACKATON Certificate",
    issuer: "IIIT Prayagraj",
    date: "2026",
    link: "https://drive.google.com/file/d/1elM2glr6Ru_VoEWLYjqPrzMs_rrabG_Q/view",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c9",
    name: "IIIT Raipur Hackaton Certificate",
    issuer: "IIIT Raipur",
    date: "2025",
    link: "https://drive.google.com/file/d/1h_-Tk8bY-VXjfIEVZRHqTqLWyVWzQAaD/view",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c10",
    name: "IIIT SURAT HACKATON Certificate",
    issuer: "IIIT Surat",
    date: "2026",
    link: "https://drive.google.com/file/d/18TixDQE5zTQ93qIK-HiIQTzc1kK2DgjA/view",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c11",
    name: "IIT Dhanbad FinTech Hackaton Certificate",
    issuer: "IIT Dhanbad",
    date: "2025",
    link: "https://drive.google.com/file/d/1w3eQsHJvBi1lo9K2EImctGLXOobp5szm/view",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c12",
    name: "IIT Gandhinagar Hackaton Certificate",
    issuer: "IIT Gandhinagar",
    date: "2025",
    link: "https://drive.google.com/file/d/1RLYaHOZQWR86ehYx3s43DHk7PwCOByM8/view",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c13",
    name: "IIT Goa Hackaton Certificate",
    issuer: "IIT Goa",
    date: "2026",
    link: "https://drive.google.com/file/d/18GimxtWztdP3GaC56DMSTUc-I80nrtjo/view",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c14",
    name: "IIT MADRAS HACKATON Certificate",
    issuer: "IIT Madras",
    date: "2026",
    link: "https://drive.google.com/file/d/1MgoWCS7PBYkeDTxnFMnKODKD04jVyZyR/view",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c15",
    name: "MICA Hackaton Certificate",
    issuer: "MICA",
    date: "2026",
    link: "https://drive.google.com/file/d/1GLnPCORsLLhLp002zrd4B_7_io8EBqbE/view",
    verified: true,
    category: "Hackathon",
  },
  {
    id: "c16",
    name: "OpenPools Certificate",
    issuer: "OpenPools",
    date: "2026",
    link: "https://drive.google.com/file/d/1Poyz64D9CInPO6iJ_IbhyomhQZakirc1/view",
    verified: true,
    category: "Academic",
  },
  {
    id: "c17",
    name: "Tech Expo 2025 Certificate",
    issuer: "Tech Expo",
    date: "2025",
    link: "https://drive.google.com/file/d/1fTOV7WWLn9X3HTYQk6Hoseftv_qIkebz/view",
    verified: true,
    category: "Competition",
  },
  {
    id: "c18",
    name: "Tech Hack Certificate",
    issuer: "Tech Hack",
    date: "2026",
    link: "https://drive.google.com/file/d/182D2hQhYf_Rwgi2pV_r08xuBZD-vvNin/view",
    verified: true,
    category: "Hackathon",
  },
];

export const hackathons = [
  {
    id: "h1",
    name: "IIIT Surat - CGPA++",
    position: "Winner 🥇 (1st Among 2nd Year)",
    date: "March 2026",
    description: "Cleared 4 intense rounds; secured 1st rank among all 2nd-year participants at IIIT Surat.",
    certificate: "https://drive.google.com/file/d/1HbOl1P_grH1Y_a3xRim7cj9m-w1a7zmE/view",
    photos: ["#"],
    location: "IIIT Surat",
    projectLink: "#",
  },
  {
    id: "h5",
    name: "IIT Gandhinagar Hackathon",
    position: "Participated (Top 100)",
    date: "November 2025",
    description: "Cleared virtual round in Top 100 teams among 5000+ participants nationwide.",
    certificate: "https://drive.google.com/file/d/1RLYaHOZQWR86ehYx3s43DHk7PwCOByM8/view",
    photos: ["#"],
    location: "IIT Gandhinagar",
    projectLink: "#",
  },
  {
    id: "h2",
    name: "Tech Expo Ahmedabad 2025",
    position: "Winner 🥇 (2nd Rank)",
    date: "April 2025",
    description: "Solo entry; secured 2nd rank among 55+ teams at Rai University.",
    certificate: "https://drive.google.com/file/d/1fTOV7WWLn9X3HTYQk6Hoseftv_qIkebz/view",
    photos: ["#"],
    location: "Ahmedabad, Gujarat",
    projectLink: "#",
  },
  {
    id: "h3",
    name: "IIIT Surat Re-Imagination",
    position: "Winner 🥇 (2nd Rank)",
    date: "February 2026",
    description: "Solo 2nd rank achievement demonstrating strong individual technical and problem-solving performance.",
    certificate: "https://drive.google.com/file/d/18TixDQE5zTQ93qIK-HiIQTzc1kK2DgjA/view",
    photos: ["#"],
    location: "IIIT Surat",
    projectLink: "#",
  },
  {
    id: "h4",
    name: "Charusat × Ocean Lab",
    position: "Participated (Top 100)",
    date: "May 2026",
    description: "Selected for offline round in Top 100 among 502 teams in a 48-hour intensive hackathon.",
    certificate: "https://drive.google.com/file/d/1MC61jiZiyJElXiJcBxV4HA47PiaQNnXw/view",
    photos: ["#"],
    location: "Changa, Gujarat",
    projectLink: "#",
  },
  {
    id: "h6",
    name: "IIIT Naya Raipur",
    position: "Finalist 🎯",
    date: "December 2025",
    description: "Travelled 2580 kilometers to participate in the prestigious national finals at Raipur.",
    certificate: "https://drive.google.com/file/d/1h_-Tk8bY-VXjfIEVZRHqTqLWyVWzQAaD/view",
    photos: ["#"],
    location: "Raipur, Chhattisgarh",
    projectLink: "#",
  },
  {
    id: "h7",
    name: "OpenPools",
    position: "Top 10 🌟 (8th Rank)",
    date: "April 2026",
    description: "Collaborated fully virtually to secure 8th position in a competitive global online hackathon.",
    certificate: "https://drive.google.com/file/d/1Poyz64D9CInPO6iJ_IbhyomhQZakirc1/view",
    photos: ["#"],
    location: "Virtual",
    projectLink: "#",
  },
  {
    id: "h8",
    name: "DAIICT Innovation Hackathon",
    position: "Participated (Top 10 Innovation)",
    date: "February 2026",
    description: "Selected for offline round beating 452+ teams; recognized for top 10 innovation.",
    certificate: "https://drive.google.com/file/d/1s2z2RL36smr-U5KpfezmxnchPMtX7-AN/view",
    photos: ["#"],
    location: "Gandhinagar, Gujarat",
    projectLink: "#",
  },
  {
    id: "h9",
    name: "Adani University Hackathon",
    position: "Participated (Top 75)",
    date: "April 2026",
    description: "Cleared virtual round in Top 75 teams among 4500+ participants.",
    certificate: "https://drive.google.com/file/d/1yJcn17Uv-kS_De2WncJXkl9KfAAOv745/view",
    photos: ["#"],
    location: "Gandhinagar, Gujarat",
    projectLink: "#",
  },
  {
    id: "h10",
    name: "Tech Hack 2025",
    position: "Participated",
    date: "April 2025",
    description: "Participated in an offline hackathon with a 4-member team at Rai University.",
    certificate: "https://drive.google.com/file/d/182D2hQhYf_Rwgi2pV_r08xuBZD-vvNin/view",
    photos: ["#"],
    location: "Ahmedabad, Gujarat",
    projectLink: "#",
  },
  {
    id: "h11",
    name: "IIIT Surat Dev Heat",
    position: "Participated (11th Rank)",
    date: "February 2026",
    description: "Secured 11th position among 95 final offline teams in a highly competitive environment.",
    certificate: "Not released yet",
    photos: ["#"],
    location: "Surat, Gujarat",
    projectLink: "#",
  },
  {
    id: "h12",
    name: "Odoo Virtual Round (IIT Gandhinagar)",
    position: "Finalist 🎯",
    date: "October 2025",
    description: "Qualified virtual round; selected for offline finals among 5000+ teams.",
    certificate: "https://drive.google.com/file/d/1RLYaHOZQWR86ehYx3s43DHk7PwCOByM8/view",
    photos: ["#"],
    location: "Virtual",
    projectLink: "#",
  },
  {
    id: "h13",
    name: "Odoo Virtual Round (Adani University)",
    position: "Finalist 🎯",
    date: "April 2026",
    description: "Qualified virtual round; selected for offline finals among 4500+ teams.",
    certificate: "https://drive.google.com/file/d/1yJcn17Uv-kS_De2WncJXkl9KfAAOv745/view",
    photos: ["#"],
    location: "Virtual",
    projectLink: "#",
  },
];
